server:
  port: 8090
spring:
  datasource:
    dynamic:
      primary: master       #设置默认的数据源或者数据源组，默认值即为master
      strict: false         #严格匹配数据源，默认false。true未匹配到指定数据源时抛异常，false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/test_master?characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver     #3.2.0开始支持SPI可省略此配置
        slave:
          url: jdbc:mysql://127.0.0.1:3306/test_slave?characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wbnull.springbootdemo.entity